#pragma once

#ifndef _FE25519_H_
#define _FE25519_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <string.h>
#include "curve25519.h"

#if defined(__GNUC__) || defined(__clang__)
#define FE25519_INLINE static __inline__ __attribute__((always_inline))
#else
#define FE25519_INLINE static inline
#endif

/**
 * @brief Field element for GF(2^255 - 19).
 *
 * Internal representation uses 10 limbs in alternating
 * 26-bit / 25-bit layout generated by the fiat-crypto
 * unsaturated-solinas backend.
 *
 * Limb bounds:
 *
 * - v[0] < 2^26
 * - v[1] < 2^25
 * - v[2] < 2^26
 * - v[3] < 2^25
 * - v[4] < 2^26
 * - v[5] < 2^25
 * - v[6] < 2^26
 * - v[7] < 2^25
 * - v[8] < 2^26
 * - v[9] < 2^25
 *
 * Field modulus:
 *
 * @f[
 * p = 2^{255} - 19
 * @f]
 */
typedef struct
{
    uint32_t v[10];
} fe25519_t;


/*
 * Field arithmetic operations.
 *
 * All operations are performed modulo:
 *
 *   p = 2^255 - 19
 *
 * Inputs and outputs are expected to be in normalized or
 * partially reduced fiat-crypto compatible representation.
 *
 * Unless otherwise specified, output values are reduced into
 * the canonical field range.
 */

/**
 * @brief Set field element to zero.
 *
 * @param[out] z Output field element.
 */
FE25519_INLINE void fe25519_zero(fe25519_t* z)
{
    memset(z, 0, sizeof(fe25519_t));
}

/**
 * @brief Set field element to one.
 *
 * @param[out] z Output field element.
 */
FE25519_INLINE void fe25519_one(fe25519_t* z)
{
    fe25519_zero(z);
    z->v[0] = 1;
}

/**
 * @brief Copy field element.
 *
 * @param[out] dst Destination field element.
 * @param[in]  src Source field element.
 */
FE25519_INLINE void fe25519_copy(fe25519_t* dst, const fe25519_t* src)
{
    memcpy(dst, src, sizeof(fe25519_t));
}

/**
 * @brief Field addition modulo p.
 *
 * Computes:
 *
 * @f[
 * out = a + b \pmod p
 * @f]
 *
 * @param[out] out Result field element.
 * @param[in]  a   Left operand.
 * @param[in]  b   Right operand.
 */
FE25519_INLINE void fe25519_add(fe25519_t* out, const fe25519_t* a, const fe25519_t* b)
{
    fiat_25519_add(out->v, a->v, b->v);
    fiat_25519_carry(out->v, out->v);
}

/**
 * @brief Field subtraction modulo p.
 *
 * Computes:
 *
 * @f[
 * out = a - b \pmod p
 * @f]
 *
 * @param[out] out Result field element.
 * @param[in]  a   Left operand.
 * @param[in]  b   Right operand.
 */
FE25519_INLINE void fe25519_sub(fe25519_t* out, const fe25519_t* a, const fe25519_t* b)
{
    fiat_25519_sub(out->v, a->v, b->v);
    fiat_25519_carry(out->v, out->v);
}

/**
 * @brief Field negation modulo p.
 *
 * Computes:
 *
 * @f[
 * out = -a \pmod p
 * @f]
 *
 * @param[out] out Result field element.
 * @param[in]  a   Input field element.
 */
FE25519_INLINE void fe25519_neg(fe25519_t* out, const fe25519_t* a)
{
    fiat_25519_opp(out->v, a->v);
    fiat_25519_carry(out->v, out->v);
}

/**
 * @brief Field multiplication modulo p.
 *
 * Computes:
 *
 * @f[
 * out = a \times b \pmod p
 * @f]
 *
 * @param[out] out Result field element.
 * @param[in]  a   Left operand.
 * @param[in]  b   Right operand.
 */
FE25519_INLINE void fe25519_mul(fe25519_t* out, const fe25519_t* a, const fe25519_t* b)
{
    fiat_25519_carry_mul(out->v, a->v, b->v);
}

/**
 * @brief Field squaring modulo p.
 *
 * Computes:
 *
 * @f[
 * out = a^2 \pmod p
 * @f]
 *
 * @param[out] out Result field element.
 * @param[in]  a   Input field element.
 */
FE25519_INLINE void fe25519_square(fe25519_t* out, const fe25519_t* a)
{
    fiat_25519_carry_square(out->v, a->v);
}

/**
 * @brief Multiply field element by Curve25519 constant 121666.
 *
 * Computes:
 *
 * @f[
 * out = 121666 \times a \pmod p
 * @f]
 *
 * Used by the Montgomery ladder implementation.
 *
 * @param[out] out Result field element.
 * @param[in]  a   Input field element.
 */
FE25519_INLINE void fe25519_mul121666(fe25519_t* out, const fe25519_t* a)
{
    fiat_25519_carry_scmul_121666(out->v, a->v);
}

/**
 * @brief Tighten field element limb bounds.
 *
 * Applies the fiat-crypto carry chain to bring each limb within its
 * designated bit-width (tight bounds).  The result is mathematically
 * equivalent mod p but is NOT guaranteed to be the unique canonical
 * representative in [0, p).  Use fe25519_tobytes + fe25519_frombytes
 * when a fully canonical form is required (e.g. before comparison).
 *
 * @param[in,out] out Field element to tighten.
 */
FE25519_INLINE void fe25519_reduce(fe25519_t* out)
{
    fiat_25519_carry(out->v, out->v);
}

/**
 * @brief Constant-time conditional swap.
 *
 * If @p swap is non-zero, swaps @p a and @p b.
 * Otherwise, no operation is performed.
 *
 * This function avoids secret-dependent branches and is
 * intended for use in the Montgomery ladder.
 *
 * @param[in,out] a    First field element.
 * @param[in,out] b    Second field element.
 * @param[in]     swap Swap control flag.
 */
FE25519_INLINE void fe25519_cswap(fe25519_t* a, fe25519_t* b, uint32_t swap)
{
    uint32_t mask = (uint32_t)(-(int32_t)(swap & 1));
    for (size_t i = 0; i < 10; i++) {
        uint32_t diff = mask & (a->v[i] ^ b->v[i]);
        a->v[i] ^= diff;
        b->v[i] ^= diff;
    }
}

/**
 * @brief Decode field element from 32-byte little-endian input.
 *
 * Input is interpreted modulo @f$p@f$.
 *
 * @param[out] out Output field element.
 * @param[in]  in  32-byte little-endian input.
 */
FE25519_INLINE void fe25519_frombytes(fe25519_t* out, const uint8_t in[32])
{
    fiat_25519_from_bytes(out->v, in);
}

/**
 * @brief Encode field element into canonical 32-byte
 * little-endian representation.
 *
 * @param[out] out 32-byte output buffer.
 * @param[in]  in  Input field element.
 */
FE25519_INLINE void fe25519_tobytes(uint8_t out[32], const fe25519_t* in)
{
    fiat_25519_to_bytes(out, in->v);
}

/**
 * @brief Constant-time field element equality test.
 *
 * @param[in] a First field element.
 * @param[in] b Second field element.
 *
 * @retval 1 Field elements are equal.
 * @retval 0 Field elements are not equal.
 */
FE25519_INLINE int fe25519_equal(const fe25519_t* a, const fe25519_t* b)
{
    /*
     * Serialise both elements through to_bytes which performs a full
     * canonical reduction to [0, p), guaranteeing a unique byte string
     * for every field value regardless of the internal limb representation.
     *
     * The comparison is constant-time: diff accumulates all byte
     * differences via OR, then the final result is derived with a
     * branch-free bitmask rather than a conditional branch.
     */
    uint8_t ba[32], bb[32];
    fiat_25519_to_bytes(ba, a->v);
    fiat_25519_to_bytes(bb, b->v);

    uint8_t diff = 0;
    for (size_t i = 0; i < 32; i++) {
        diff |= ba[i] ^ bb[i];
    }

    /* Produce 1 if diff==0, 0 otherwise — no branch on secret data. */
    uint32_t d = (uint32_t)diff;
    return (int)(1u - ((d | (0u - d)) >> 31));
}

/**
 * @brief Constant-time zero test.
 *
 * @param[in] a Input field element.
 *
 * @retval 1 Field element is zero.
 * @retval 0 Field element is non-zero.
 */
FE25519_INLINE int fe25519_iszero(const fe25519_t* a)
{
    /* Use byte serialisation for canonical form; compare constant-time. */
    uint8_t ba[32];
    fiat_25519_to_bytes(ba, a->v);

    uint8_t sum = 0;
    for (size_t i = 0; i < 32; i++) {
        sum |= ba[i];
    }

    /* Branch-free: sum==0 iff zero element. */
    uint32_t s = (uint32_t)sum;
    return (int)(1u - ((s | (0u - s)) >> 31));
}

/**
 * @brief Compute multiplicative inverse modulo p.
 *
 * Computes:
 *
 * @f[
 * out = z^{-1} \pmod p
 * @f]
 *
 * Typically implemented using exponentiation:
 *
 * @f[
 * z^{p-2}
 * @f]
 *
 * @param[out] out Result field element.
 * @param[in]  z   Input field element.
 */
void fe25519_invert(fe25519_t* out, const fe25519_t* z);

#ifdef __cplusplus
}
#endif

#endif /* end of _FE25519_H_ */
